travis:
  secure:
    BINSTAR_TOKEN: Xp6oyqZacRGpSnV0VE9t+/l37WwnY2LhlYpyxgSx24F+lhBe1l0KVHeuZ0jgyhTCH702GeeYt9feYk32kvyldv2+47TisRWlQ/kITYttG9EceO1OGllua+UhXLU1splsMDyDVNL51W2xH1AUYLZPZC2Nwf5DdipgKRbICtga+U/ryu7YFucuWdgCw+b4UWK6Ijq5weXqdLZ06oYBPXruCaA0nDMHNOgUomIJVr4jD51WZrAo3aEyNyZ75Q7DhzrYira5CpB6ysFaQqqFbEOCcuzrlqHzYHHiuPx41acYyZ7XF6wzWBjELNj8gUc9iiNy+AyiQzQEkQ79jdntKbxqfrHvBRU5lFRWoxXbpR/dA1L2vSjCrN27+KpqH/HY2FqulPkwd0yw3bPdUgfJp4dN1J6M4pkQcR9Fq2Fv9I4W9jek5MacGt43cnPI9eDrcaAedSjdcIDGa4pOvYR49T7rRhVVs1CvViGIkwDKrhYCLPmDFn86ix7H8buXKxkQV5x5i8OMT8f3s3yr3kFWgnmVQeauh4rUjLZgPxCddGSon8+t4kg9R1wI72wUXStVe2OxjYdXO0ilUDMpeoALNMMPoeIb+/RD9PipJcWuLsIFPGL2At4bCMfYIWAXrzZDg/NPpwATmt8P4+5lq3/VK0lxsCbhRrXr7SOXv9f1fVzkfoA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
