appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Iyz65P5spZJH+ahED+T4dcZUGazk3Mm/2VkPzIjP0lVdFD87zZzz3MpcuaL2EWGhzl1+K2BUKGLcc1w4M/KGpmb9SGA5lp93Jh0Q/O4qUZbzevfr/LZrDCr/d50gzCF/3mazGQ/pj5RIabdUOrOWZ+DY3IW8XPTKRH7o4Ri/RGememz99Ndpw1MXBn3jn+C0jMof6JTfKxDjbWq+RCUHlwgYAbi9h2heXEeTh7i11pbnL4w35UwyGFcJBJQj/F7tMPzYoD81EL90CaAtY+hF+MrI453Woa4l85sQnd+F2zclQ6vgD4aSwWvjxyPezJS2TckVNiNZlIxYzDBRzyHc2ptGEFyyQfeEN6QWS21sq7CM+U05r3/KqLRX6e9/u8tsI0f+aihgyOp2PeCPH4aXGI7XYKYjzzVGM+57jFhYbfz6vYKmHhKwGQg7idNRYyzPlPffajTZki31UXniM33e0DGB7t4bF8Og91I+OXpT8GQtzRG82nqPlBaCWMvbIw+62fnv4+1xq5VbowqeI4ed9808XTF9Y0f/wIPyaTmMjBd/CAhApT/ZKJ0DYMoqdhegCBA88KSTww58kWsmByKCzuzj6DAIhgS0IC9fwqer9l55A6pZE1F+MQ+AgiW6wU+1ApzM+fYzasZ4DP1vSILowxs1AYK4oE8pCw7/IsLCLyE=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
